### PR TITLE
Support for hashed token

### PR DESCRIPTION
**Pull request by Zefau**
This adds support for hashed token.
Since I do not own a hardware bridge, I would appreciate if you could verify and test the added code.

See #8 

Thanks in advanced and kind regards,
Zefau

### CODE REVIEW

**Comment by Mik13** [comment]
Thank you very much in advance! I've commented some changes. I will test it within the next few weeks, when my HW-Bridge is available again

**Comment by Zefau** [comment]
@Mik13 Have you had the time to give this a try? Thanks and kind regards

**Comment by Zefau** [comment]
Thanks again for all your help.
I was wondering if you got any further on this here or if you have a rough timeline?

I could also ask around to get it tested on a hardware bridge by someone?

**Comment by Mik13** [comment]
Sadly I didn't have any access yet, but I hope in the next 2 week.

If anyone else would test it with a hardware bridge and confirms that it works I would be more than happy to accept the PR.

Thanks for your help!

**Comment by Zefau** [comment]
Due to the changes in this library in the meanwhile, the code base for my pr is outdated.
I created a new forked based on the latest version of this repo and re-applied my changes, see https://github.com/Zefau/nuki-bridge-api/tree/rebase.

I found a tester and will come back with a new pr soon (hopefully).
If you find the possibility to test, you're very welcome.

Cheers
Zefau

**Pull request closed without merging**
