### PR TITLE
added support for different deviceTypes

### PR DESCRIPTION
**Pull request by Zefau**

### CODE REVIEW

**Comment by Zefau** [comment]
The git command line is driving me nuts. Can't get the lost commit restored and proper squashed again. Here's a new pr now. Hope this fits now finally.

**Comment by Zefau** [comment]
@Mik13

**Comment by Mik13** [comment]
:tada: 

Thank you very much @Zefau!

Just published 1.6.0 to npm with your feature.

**Comment by Zefau** [comment]
Woop woop! We made it :-)

**Pull request merged**
