### PR TITLE
added delay

### PR DESCRIPTION
**Pull request by Zefau**
I added a little delay due to the requests being sent too often in a short time frame, which apparently causes issue for some users.
See issue https://github.com/Zefau/ioBroker.nuki2/issues/9 for more information.

Thanks in advanced and kind regards,
Zefau

### CODE REVIEW

**Comment by Mik13** [comment]
After reading the issue it looks like it would be better idea to ensure that every request will be seperated by a delay and not just this one.

If you confirm, I will add this next week.

**Comment by Zefau** [comment]
It is indeed. As going further with the analysis in the issue, we have figured out the next bottleneck, [as seen here](https://github.com/Zefau/ioBroker.nuki2/issues/9#issuecomment-489370466). This one is due to my implementation.
If every request can be separated though, this would be very helpful.

Thanks and kind regards,
Zefau

**Comment by Mik13** [comment]
I've implemented a method which does return a non-delayed promise, and still ensures a configurable 250ms delay between requests (all requests, nuki, bridge and callback).
You can find it in the "delay" branch.

Please test and report back, sadly I still does not have my nuki available.

Thanks in advance!

**Comment by Zefau** [comment]
Thank you very much for your effort. Works as expected, see https://github.com/Zefau/ioBroker.nuki2/issues/9#issuecomment-489422043.

**Comment by Mik13** [comment]
I have published version 1.4.0.

Thank you very much!

**Comment by Zefau** [comment]
Could you have a look at the current discussion in https://github.com/Zefau/ioBroker.nuki2/issues/9#issuecomment-489748368 whether this might be related to the newly added delay or might be caused of something else?

**Comment by Mik13** [comment]
I've commented in you issue. I hope this is ok for you

**Pull request closed without merging**
