### PR TITLE
 Support for hashed token

### PR DESCRIPTION
**Pull request by Zefau**
see https://github.com/Mik13/nuki-bridge-api/issues/8

### CODE REVIEW

**Comment by Zefau** [comment]
I had to add `forcePlainToken` parameter, because if the bridge type is unknown the first request has to be send with plain/cleartext token (unfortunately).

Another approach could be to send the hash token and re-send the plan token if the request fails, what do you think?

Additionally, I ran into problems because I had to retrieve the bridge type on instantiation (before sending any request) so I used `async`/`await`. I'm not very satisfied with the source code now though. Maybe you have a better idea to refactor the code?

Thanks and kind regards,
Zefau

**Comment by Zefau** [comment]
Hi,

have you had the time to look at this? Unfortunately I could not really get into testing this with anybody (since it is challenging being remote).

If you find the time I appreciate it.

Cheers,
Zefau

**Comment by Mik13** [comment]
Hi!

Sorry for the long delay, I will look into it in the next few weeks!

Best regards!

**Comment by Mik13** [comment]
I've reviewed the pull request and it looks really good. Thanks for the great work!

Please resolve the few comments I've left and I will happily accept it. If you need help with something, just call ;)

**Comment by Zefau** [comment]
I would appreciate if you could have a look at this. Since I don't own a Hardware Bridge myself and since it is quite challenging to remote debug with someone that owns one, it would be great if you could look at this.

Thanks in advanced,
Zefau

**Comment by Zefau** [comment]
@Mik13 Ok, don't worry anymore. I bought a Hardware Bridge now, because apparently the Nuki Opener does not work with a Software Bridge.
I'm closing this for now, because my implementation suggestion will always send the first request with plain token, because it is unclear whether is it talking to Hardware or Software Bridge.

I will refactor it in a way, that always a hashed token is send first and when the request fails, a plain token is used instead.

What do you think?

**Pull request closed without merging**
