### PR TITLE
response.success is a string value

### PR DESCRIPTION
**Pull request by mwittig**
See page 4 of the APIdoc https://nuki.io/wp-content/uploads/2016/04/Bridge-API-v1.02.pdf

### CODE REVIEW

**Comment by Mik13** [comment]
Did you test that with a real Bridge? Mine seems to return a boolean instead of a string.

**Comment by mwittig** [comment]
No I have tested with https://github.com/benzman81/nukiio-dummy-bridge and studied rthe official bridge API documentation https://nuki.io/wp-content/uploads/2016/04/Bridge-API-v1.02.pdf

If your bridge return a boolean value, may be the API documentation is wrong! 
To mitigate this my suggestion is to change the condition as follows: 

```
if (response.success === true || response.success === "true")

**Comment by Mik13** [comment]
Sounds good to me.

Could you please edit your commit? I will merge it afterwards.

And the dummy bridge looks interesting too, I will look into that later this week.

**Comment by mwittig** [comment]
Done! I'll also contact nukio.io to get a clarification on this. Maybe it is doumentation bug, or they changed the implementation from an earlier version of the bridge API and did not update the API doc.

**Comment by Mik13** [comment]
Thank you very much!

Please keep me updated what the guys from nuki.io responded.

**Comment by mwittig** [comment]
OK, will do

**Comment by mwittig** [comment]
Hi. I got a response from Nuki. Hope, you can read German. Basically, they are confirming it is a documentation bug.

```
Betreff: 	Re: Frage zur Bridge API-Dokumentation version 1.02
Datum: 	Tue, 04 Oct 2016 14:59:59 +0000
Von: 	Thomas <contact@nuki.io>
An: 	M. Wittig <wittigmarcus@googlemail.com>



Re: Frage zur Bridge API-Dokumentation version 1.02
Hallo Marcus,

Danke für das Feedback.

In der Dokumentation ist leider ein Fehler, welchen wir aber noch
ausbessern.

Für Entwickler haben wir leider keine Test Bridge verfügbar.

Schöne Grüße,
Thomas

*Customer Support*

*Nuki Home Solutions GmbH*
Münzgrabenstraße 92/4
8010 Graz, Austria

nuki.io
www.facebook.com/nuki.smartlock
www.twitter.com/nuki_smartlock

M. Wittig <wittigmarcus@googlemail.com
<mailto:wittigmarcus@googlemail.com>> schrieb am 3. Oktober 2016 um 5:43
NACHMITTAGS:

    Hallo,

    In der Bridge API-Dokumentation v1.02 steht auf Seite 5, dass in der
    "/lockState" Response-Nachricht das Element "success" ein String-Wert
    "true" oder "false" liefert. Die aktuelle Bridge Firmware scheint
    hier aber
    eine Boolean-Wert zu liefern.

    Meine Frage: Wurde der Elementtyp gegenüber einer früheren
    Firmware-Version geändert (und die Doku nicht angepasst) oder
    handelt es sich hier generell um einen Dokumentationsfehler?

    Eine weitere Frage: Gibt es von Eurer Seite für Entwickler eine
    MockUp-Bridge zu Testzwecken, z.B. auf der Basis von Swagger? Bei
    meinen Recherchen bin auf das Projekt
    https://github.com/benzman81/nukiio-dummy-bridge gestossen, dass sich
    allerdings noch in einem fühen Stadium befindet und daher nicht
    unbedingt die "Quelle der Wahrheit" ist :)

    Vielen Dank und Freundlichen Grüße
    Marcus Wittig

powered by UserVoice.
<http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=Nuki+Home+Solutions+GmbH&uv_contact_url=nukihomeso.uservoice.com&uv_experience=email>

**Comment by Mik13** [comment]
Thank you very much, glad that issue resolves soon.

And yes, german is my first language.

**Pull request merged**
